(*@PROPERTIES_EX@
TYPE: POU
LOCALE: 0
IEC_LANGUAGE: ST
PLC_TYPE: independent
PROC_TYPE: independent
GROUP: EMULATION
*)
(*@KEY@:DESCRIPTION*)

(*@KEY@:END_DESCRIPTION*)
FUNCTION_BLOCK DATE_TO_STRING

(*Group:Default*)


VAR_INPUT
	IDATE :	UDINT;
END_VAR


VAR_OUTPUT
	DATE_STRING :	STRING;
END_VAR


VAR
	st_tmp1 :	STRING;
END_VAR


(*@KEY@: WORKSHEET
NAME: DATE_TO_STRING
IEC_LANGUAGE: ST
*)
st_tmp1 := CONCAT(INT_TO_STRING(YEAR_OF_DATE(IDATE),'%04d-'),INT_TO_STRING(MONTH_OF_DATE(IDATE),'%02d-'));
DATE_STRING := CONCAT(st_tmp1,INT_TO_STRING(day_of_month(IDATE),'%02d'));
(*@KEY@: END_WORKSHEET *)
END_FUNCTION_BLOCK
