(*@PROPERTIES_EX@
TYPE: POU
LOCALE: 0
IEC_LANGUAGE: ST
PLC_TYPE: independent
PROC_TYPE: independent
GROUP: SETUP
*)
(*@KEY@:DESCRIPTION*)

(*@KEY@:END_DESCRIPTION*)
FUNCTION SETUP_EXTENDED_ASCII:BOOL

(*Group:Default*)


VAR_INPUT
	X :	BOOL;
END_VAR


(*@KEY@: WORKSHEET
NAME: SETUP_EXTENDED_ASCII
IEC_LANGUAGE: ST
*)
(* setup Parameters *)
SETUP_EXTENDED_ASCII := X OR TRUE; (* Dummy damit VAR_INPUT auch benutzt wird *)
(*@KEY@: END_WORKSHEET *)
END_FUNCTION
