(*@PROPERTIES_EX@
TYPE: POU
LOCALE: 0
IEC_LANGUAGE: ST
PLC_TYPE: independent
PROC_TYPE: independent
GROUP: EMULATION
*)
(*@KEY@:DESCRIPTION*)

(*@KEY@:END_DESCRIPTION*)
FUNCTION TIME_TO_REAL:REAL

(*Group:Default*)


VAR_INPUT
	X :	TIME;
END_VAR


(*@KEY@: WORKSHEET
NAME: TIME_TO_REAL
IEC_LANGUAGE: ST
*)
TIME_TO_REAL := UDINT_TO_REAL(DINT_TO_UDINT(TIME_TO_DINT(X)));
(*@KEY@: END_WORKSHEET *)
END_FUNCTION
