(*@PROPERTIES_EX@
TYPE: POU
LOCALE: 0
IEC_LANGUAGE: ST
PLC_TYPE: independent
PROC_TYPE: independent
GROUP: EMULATION
*)
(*@KEY@:DESCRIPTION*)
UDINT_TO_TIME := DINT_TO_TIME(UDINT_TO_DINT(IN));
(*@KEY@:END_DESCRIPTION*)
FUNCTION UDINT_TO_TIME:TIME

(*Group:Default*)


VAR_INPUT
	IN :	UDINT;
END_VAR


(*@KEY@: WORKSHEET
NAME: UDINT_TO_TIME
IEC_LANGUAGE: ST
*)
UDINT_TO_TIME := DINT_TO_TIME(UDINT_TO_DINT(IN));
(*@KEY@: END_WORKSHEET *)
END_FUNCTION
